[fast_rcnn] Fix the selected anchors for inference
- The ground_truth boxes transformation where used instead of sampling the anchors
which lead to no training

- Add a -1 in the transform_fpcoord_for_tf following this error message:

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument:  ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1
	 [[node model/fast_rcnn/concat_13 (defined at /usr/local/lib/python3.6/dist-packages/od/core/box_ops.py:47) ]]
	 [[model/fast_rcnn/mean_absolute_error/weighted_loss/broadcast_weights/assert_broadcastable/AssertGuard/pivot_f/_172/_379]]